### PR TITLE
Add Stride Logo

### PR DESCRIPTION
**Pull request by jsouth**
This PR resolves issue #123 by adding the stride logo for the Mothership app to consume.

screenshot 2018-06-22 09 34 34

### CODE REVIEW

**Comment by jsouth** [comment]
@ryanjwilke - As this is not urgent,  I would like to make sure I understand whats going down :)

In version.rb we have
```VERSION = '0.9.0'```

What version should it be bumped to?  Not seeing where the desired version is being requested in build logs.

Snippet from the build log that I was zoning in on, but not sure its the actual issue.

```....
 setup'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/lib/bundler/runtime.rb:313:in `check_for_activated_spec!': **You have already activated eventmachine 1.2.7, but your Gemfile requires eventmachine 1.2.5. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)**```

**Comment by ryanjwilke** [comment]
@jsouth I think we should bump the version to `1.0.0` in this case. I also this we should adopt a model such as this: `:major/:minor/:fix`. In reality, we have lots of `minor` updates so I think `0-100` makes more sense for that scale. Does that makes sense to you? Proper versioning is a little new to me, but I've been schooled on this recently from @codebryo so hopefully we're on the right track now ;)

Shipyard is stable enough now to bump it to `1.0.0` in my opinion.

**Comment by ryanjwilke** [comment]
On a side note, I wonder if this becomes irrelevant soon anyways since Slack just bought HipChat and Stride and plans to shut them down 🤔

**Comment by jsouth** [comment]
@ryanjwilke 
Yes. This versioning scale makes perfect sense.

👍 Will bump to 1.0.

Whoa! haha. Thats exciting news to wake up to.

**Comment by jsouth** [comment]
stride == gone. Closing this PR.

**Pull request closed without merging**
